plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.moyuinstaller'
version = '1.0.0'

android {
  namespace "expo.modules.moyuinstaller"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'androidx.core:core:1.17.0'
}
